import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Catagories from '@/components/Catagory';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Next News App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang='en'
			className=''
		>
			<body className={inter.className}>
				<main className='max-w-full max-h-full px-8 md:px-32 dark:bg-slate-800'>
					<Header />
					{children}
					<Footer />
				</main>
			</body>
		</html>
	);
}
